server:
  port: 8080
  servlet:
    context-path: /compliance
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  devtools:
    restart:
      enabled: true  #开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  application:
    name: compliance
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  servlet: 
    multipart:
      enabled: true #表示是否开启文件上传支持，默认为 true
      location: D:/  #用来指定上传文件的临时写入目录,一定要注意是绝对目录(linux注释该配置)
      file-size-threshold: 1KB   #默认为0，即没有限制
      max-file-size: 20MB       #上传的单个文件的最大大小，默认为 1MB
      max-request-size: 100MB    #多文件上传时文件的总大小，默认为 10MB
      resolve-lazily: false    #表示文件是否延迟解析，默认为 false
  datasource:
     #账号配置
     url: jdbc:mysql://rm-bp1q1ik16aml2ixg9ko.mysql.rds.aliyuncs.com:3306/compliance?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
     username: huiyan
     password: F848369B180D3E48D46A2ED439F2DDCD
     driver-class-name: com.mysql.cj.jdbc.Driver
     type: com.ljh.yqvalley.ValleyHikariDataSource
     hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 20 #连接池最大连接数，默认是20
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
      connection-init-sql: set names utf8mb4
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 595BC41AD75ECF36B7219852F2BF2B6E
      timeout: 3000ms
      database: 0
  ai:
    openai:
      client:
        enabled: false
      api-key: 你的API_KEY
      base-url: https://api.openai.com
mybatis:
  mapper-locations: classpath*:com/ljh/yqvalley/**/dao/*Mapper.xml,com/isoftstone/compliance/**/dao/*Mapper.xml
  type-aliases-package: com.ljh.yqvalley.**.model,com.isoftstone.compliance.**.model
logging:
  config: classpath:logback-spring.xml
  path: /home/release/compliance/log
yqv:
  authorityPackage: com.ljh.yqvalley.*,com.isoftstone.compliance.*
  authorityModuleCode: yqv,compliance
  authorityModuleName: 框架,企业合规
  filePath: /home/release/compliance
  redisKey: compliance_dev_
  aesPublicKey: 31FFC9CFFD9E5AEB